language: cpp

matrix:
  include:
    - name: Ubuntu 16.04 LTS + gcc
      os: linux
      dist: bionic
      sudo: required
      compiler: gcc
      script:
        - sh BuildScripts/travis_build.sh
	- name: Ubuntu 18.04 LTS + gcc
      os: linux
      dist: bionic
      sudo: required
      compiler: gcc
      script:
        - sh BuildScripts/travis_build.sh

  before_install:
    - eval "${MATRIX_EVAL}"